"""added created_at column to user table

Revision ID: 45d0747aa4f2
Revises: ffdc0a98111c
Create Date: 2021-03-30 11:26:44.724283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d0747aa4f2'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_on')
    # ### end Alembic commands ###
