"""added show column to reviews

Revision ID: 67778844b7c3
Revises: 5314e77c0974
Create Date: 2021-04-20 14:57:50.971582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67778844b7c3'
down_revision = '5314e77c0974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('show_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'reviews', 'shows', ['show_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'show_id')
    # ### end Alembic commands ###
