"""added lats and lngs to shows

Revision ID: 2dcdfdbd62b4
Revises: 6b67d0f98503
Create Date: 2021-04-02 14:41:28.276055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dcdfdbd62b4'
down_revision = '6b67d0f98503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('address', sa.String(length=255), nullable=False))
    op.add_column('shows', sa.Column('location_lat', sa.Integer(), nullable=False))
    op.add_column('shows', sa.Column('location_lng', sa.Integer(), nullable=False))
    op.drop_column('shows', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('shows', 'location_lng')
    op.drop_column('shows', 'location_lat')
    op.drop_column('shows', 'address')
    # ### end Alembic commands ###
