"""empty message

Revision ID: 1e53fcd17c6d
Revises: d6089bede3c7
Create Date: 2021-04-01 18:36:19.656919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e53fcd17c6d'
down_revision = 'd6089bede3c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('temp', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'temp')
    # ### end Alembic commands ###
