"""added rating column to artists

Revision ID: 5d7e3188a747
Revises: 67778844b7c3
Create Date: 2021-04-20 18:49:12.522652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d7e3188a747'
down_revision = '67778844b7c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'rating')
    # ### end Alembic commands ###
