"""updated shows time and date columns

Revision ID: e0261578aa58
Revises: 1e53fcd17c6d
Create Date: 2021-04-01 18:36:46.705854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0261578aa58'
down_revision = '1e53fcd17c6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'temp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('temp', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
