"""empty message

Revision ID: 6b67d0f98503
Revises: 8e784b24ba07
Create Date: 2021-04-01 18:42:47.969469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b67d0f98503'
down_revision = '8e784b24ba07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('date', sa.String(length=255), nullable=False))
    op.add_column('shows', sa.Column('time', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'time')
    op.drop_column('shows', 'date')
    # ### end Alembic commands ###
