"""updated shows time and date columns

Revision ID: b7a2d51806d9
Revises: e0261578aa58
Create Date: 2021-04-01 18:41:09.447472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7a2d51806d9'
down_revision = 'e0261578aa58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('scription', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'scription')
    # ### end Alembic commands ###
